# Generated by Django 2.2.5 on 2019-09-19 20:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='fecha_creado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
