# Generated by Django 2.2.5 on 2019-09-26 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190919_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='texto',
            field=models.TextField(verbose_name='formfield_overrides'),
        ),
    ]
