# Generated by Django 2.2.5 on 2019-09-26 22:05

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190926_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='texto',
            field=tinymce.models.HTMLField(verbose_name='texto'),
        ),
    ]
