# Generated by Django 2.2.5 on 2019-09-27 01:31

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190926_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='texto',
            field=markdownx.models.MarkdownxField(verbose_name='texto'),
        ),
    ]
