# Generated by Django 2.2.5 on 2019-09-27 02:16

from django.db import migrations
import django_markdown.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='texto',
            field=django_markdown.models.MarkdownField(verbose_name='texto'),
        ),
    ]
