# Generated by Django 2.2.5 on 2019-09-27 02:19

from django.db import migrations
import django_markdown.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20190926_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='texto',
            field=django_markdown.models.MarkdownField(),
        ),
    ]
