# Generated by Django 2.2.5 on 2019-10-04 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191003_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='fecha_publicado',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Publicado'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='fecha_publicado',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Publicado'),
        ),
        migrations.AlterField(
            model_name='post',
            name='fecha_publicado',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Publicado'),
        ),
    ]
